In [1]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [2]:
df.columns.to_list()

['entity', 'code', 'year', 'life_expectancy_0']

In [3]:
df.rename(columns={"entity": "Pais"}, inplace=True)

In [4]:
df[df["Pais"].str.contains("K", regex=True)]

                 Pais code  year  life_expectancy_0
8148        Hong Kong  HKG  1950            57.8180
8149        Hong Kong  HKG  1951            58.7156
8150        Hong Kong  HKG  1952            59.7724
8151        Hong Kong  HKG  1953            60.8631
8152        Hong Kong  HKG  1954            61.9221
...               ...  ...   ...                ...
20382  United Kingdom  GBR  2019            81.4426
20383  United Kingdom  GBR  2020            80.3854
20384  United Kingdom  GBR  2021            80.7080
20385  United Kingdom  GBR  2022            81.0744
20386  United Kingdom  GBR  2023            81.3015

[1009 rows x 4 columns]

In [5]:
df.dropna(subset=["code"], inplace=True)
df.isnull().sum()

Pais                 0
code                 0
year                 0
life_expectancy_0    0
dtype: int64

In [6]:
df.shape

(20217, 4)

In [7]:
resultado = (
    df.groupby("Pais")["life_expectancy_0"]
    .mean()
    .sort_values(ascending=True)
)
resultado.head(10)

Pais
USSR                        32.700000
South Sudan                 37.841631
Sierra Leone                43.189605
Mali                        43.760793
Niger                       44.187513
East Timor                  44.684692
Nigeria                     44.855897
Chad                        45.007786
Central African Republic    45.084431
Malawi                      45.554985
Name: life_expectancy_0, dtype: float64

In [8]:
res_1 = df [(df["year"] >= 1970)]
res_1

              Pais code  year  life_expectancy_0
20     Afghanistan  AFG  1970            37.4601
21     Afghanistan  AFG  1971            37.9324
22     Afghanistan  AFG  1972            38.4226
23     Afghanistan  AFG  1973            38.9510
24     Afghanistan  AFG  1974            39.4687
...            ...  ...   ...                ...
21560     Zimbabwe  ZWE  2019            61.0603
21561     Zimbabwe  ZWE  2020            61.5300
21562     Zimbabwe  ZWE  2021            60.1347
21563     Zimbabwe  ZWE  2022            62.3601
21564     Zimbabwe  ZWE  2023            62.7748

[13284 rows x 4 columns]

In [9]:
resultado = (
    res_1.groupby("Pais")["life_expectancy_0"]
    .mean()
    .sort_values(ascending=True)
)

resultado.head(5)

Pais
South Sudan                 41.076146
Central African Republic    47.109006
Sierra Leone                47.234867
Chad                        47.391891
Niger                       47.716867
Name: life_expectancy_0, dtype: float64